name: sso_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  local_auth: ^2.2.0 # Fingerprint
  
  dio: ^5.4.0 # API request handling (recommended)
  provider: ^6.1.2 # State management
  
  fluttertoast: ^8.2.4 # For showing toast messages
  modal_progress_hud_nsn: ^0.5.1 # For showing loading overlay
  connectivity_plus: ^6.0.2 # For checking internet connection
  
  json_annotation: ^4.9.0 # For JSON serialization

  shared_preferences: ^2.2.3
  
  # Optional: Pretty Dio logger (debugging API requests)
  pretty_dio_logger: ^1.3.1


  permission_handler: ^11.3.1

  mobile_scanner: ^5.1.1

  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  build_runner: ^2.4.8 # Needed for json_serializable
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
